spring:
  application:
    name: auth-service
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:user
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    schema: classpath:db/schema.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

server:
  port: 19000

eureka:
  client:
    serviceUrl:
      defaultZone: http://center1:8761/eureka/,http://center2:8762/eureka/

security:
  oauth2:
    resource:
      filter-order: 3

---
spring:
  profiles: docker
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:user
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    schema: classpath:db/schema.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

server:
  port: ${{SERVER_PORT}:19000}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_LIST}

security:
  oauth2:
    resource:
      filter-order: 3
