spring:
  profiles: dev

server:
  port: ${{SERVER_PORT}:8761}

eureka:
  instance:
    hostname: ${HOSTNAME}
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    environment: dev
  client:
    fetch-registry: false
    register-with-eureka: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/,${ADDITIONAL_EUREKA_SERVER_LIST}
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000
