spring:
  profiles: dev
  application:
    name: register-center

server:
  port: ${{SERVER_PORT}:8761}

eureka:
  environment: ${spring.profiles}
  datacenter: rainbowland
  instance:
    hostname: ${HOSTNAME}
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    status-page-url-path: /info
    ipAddress: 192.168.99.100
  client:
    fetch-registry: false
    register-with-eureka: true
    server:
      waitTimeInMsWhenSyncEmpty: 0
    serviceUrl:
      defaultZone: ${ADDITIONAL_EUREKA_SERVER_LIST}
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000
