version: "2"
services:

  #启动注册中心eureka-server集群 集中管理/服务注册/服务发现
  center1:
    hostname: center1
    image: lvqiang/register-center
    ports:
      - "8761:8761"
    environment:
      - HOSTNAME=center1
      - ADDITIONAL_EUREKA_SERVER_LIST=http://center2:8762/eureka/
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8761

  center2:
    hostname: center2
    image: lvqiang/register-center
    ports:
      - "8762:8762"
    environment:
      - HOSTNAME=center2
      - ADDITIONAL_EUREKA_SERVER_LIST=http://center1:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8762
    links:
      - center1

  auth:
    hostname: auth
    image: lvqiang/auth-service
    ports:
      - "19000:19000"
    environment:
      - EUREKA_SERVER_LIST=http://center1:8761/eureka/,http://center2:8762/eureka/
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=19000
    links:
      - center1
      - center2

  # 启动 hello-service
  hello-service1:
    image: lvqiang/hello-service
    ports:
      - "10000:10000"
    environment:
      - EUREKA_SERVER_LIST=http://center1:8761/eureka/,http://center2:8762/eureka/
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT:10000
      - AUTH_SERVER_LIST=http://auth:19000/user
    links:
      - center1
      - center2

  hello-service2:
    image: lvqiang/hello-service
    ports:
      - "10001:10001"
    environment:
      - EUREKA_SERVER_LIST=http://center1:8761/eureka/,http://center2:8762/eureka/
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT:10001
      - AUTH_SERVER_LIST=http://auth:19000/user
    links:
      - center1
      - center2

