version: "2"
services:

  #启动注册中心eureka-server集群 集中管理/服务注册/服务发现
  center1:
    hostname: center1
    image: lvqiang/register-center
    ports:
      - "8761:8761"
    environment:
      - HOSTNAME=center1
      - ADDITIONAL_EUREKA_SERVER_LIST=http://center2:8762/eureka/
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=8761

  center2:
    hostname: center2
    image: lvqiang/register-center
    ports:
      - "8762:8762"
    environment:
      - HOSTNAME=center2
      - ADDITIONAL_EUREKA_SERVER_LIST=http://center1:8761/eureka/
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=8762
    links:
      - center1

  #启动user-service服务
  user-service1:
    container_name: user-service1
    image: lvqiang/user-service
    ports:
      - "10001:10001"
    environment:
      - EUREKA_SERVER_LIST=http://center1:8761/eureka/,http://center2:8762/eureka/
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=10001
    links:
      - center1
      - center2

  user-service2:
    container_name: user-service2
    image: lvqiang/user-service
    ports:
      - "10002:10002"
    environment:
      - EUREKA_SERVER_LIST=http://center1:8761/eureka/,http://center2:8762/eureka/
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=10002
    links:
      - center1
      - center2

  #启动oauth-service服务
  oauth-service1:
    container_name: oauth-service1
    image: lvqiang/oauth-service
    ports:
      - "8001:8001"
    environment:
      - EUREKA_SERVER_LIST=http://center1:8761/eureka/,http://center2:8762/eureka/
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=8001
    links:
      - center1
      - center2

  #启动网关gateway,可配置成集群,使用nginx进行负载 智能路由/安全控制/负载均衡
  gateway:
    container_name: app-api-gateway
    image: lvqiang/app-api-gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_SERVER_LIST=http://center1:8761/eureka/,http://center2:8762/eureka/
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=8080
    external_links:
      - center1
      - center2
