version: "2"
services:

  #启动注册中心eureka-server集群 集中管理/服务注册/服务发现
  center1:
    hostname: center1
    image: lvqiang/register-center
    ports:
      - "8761:8761"
    environment:
      - HOSTNAME=center1
      - ADDITIONAL_EUREKA_SERVER_LIST=http://center2:8762/eureka/,http://center3:8763/eureka/
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=8761

  center2:
    hostname: center2
    image: lvqiang/register-center
    ports:
      - "8762:8762"
    environment:
      - HOSTNAME=center2
      - ADDITIONAL_EUREKA_SERVER_LIST=http://center1:8761/eureka/,http://center3:8763/eureka/
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=8762

  center3:
    hostname: center3
    image: lvqiang/register-center
    ports:
      - "8763:8763"
    environment:
      - HOSTNAME=center3
      - ADDITIONAL_EUREKA_SERVER_LIST=http://center1:8761/eureka/,http://center2:8762/eureka/
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=8763

  # 启动rabbitmq作为消息中间件
  rabbitmq:
    container_name: rabbitmq
    image: docker.io/rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  #启动auth-service服务
  auth-service1:
    container_name: auth-service1
    image: lvqiang/auth-service
    ports:
      - "19001:19001"
    environment:
      - EUREKA_SERVER_LIST=http://center1:8761/eureka/,http://center2:8762/eureka/,http://center3:8763/eureka/
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=19001

  auth-service2:
    container_name: auth-service2
    image: lvqiang/auth-service
    ports:
      - "19002:19002"
    environment:
      - EUREKA_SERVER_LIST=http://center1:8761/eureka/,http://center2:8762/eureka/,http://center3:8763/eureka/
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=19002

