version: "2"
services:

  # 启动 product-service
  product-service1:
    container_name: product-service1
    image: lvqiang/product-service
    ports:
      - "11001:11001"
    environment:
      - EUREKA_SERVER_LIST=http://center1:8761/eureka/,http://center2:8762/eureka/
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=11001
    external_links:
      - center1
      - center2

  product-service2:
    container_name: product-service2
    image: lvqiang/product-service
    ports:
      - "11002:11002"
    environment:
      - EUREKA_SERVER_LIST=http://center1:8761/eureka/,http://center2:8762/eureka/
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=11002
    external_links:
      - center1
      - center2

  # 启动 coupon-service
  coupon-service1:
    container_name: coupon-service1
    image: lvqiang/coupon-service
    ports:
      - "12001:12001"
    environment:
      - EUREKA_SERVER_LIST=http://center1:8761/eureka/,http://center2:8762/eureka/
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=12001
    external_links:
      - center1
      - center2

  coupon-service2:
    container_name: coupon-service2
    image: lvqiang/coupon-service
    ports:
      - "12002:12002"
    environment:
      - EUREKA_SERVER_LIST=http://center1:8761/eureka/,http://center2:8762/eureka/
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=12002
    external_links:
      - center1
      - center2

  # 启动 order-service
  order-service1:
    container_name: order-service1
    image: lvqiang/order-service
    ports:
      - "13001:13001"
    environment:
      - EUREKA_SERVER_LIST=http://center1:8761/eureka/,http://center2:8762/eureka/
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=13001
    external_links:
      - center1
      - center2

  order-service2:
    container_name: order-service2
    image: lvqiang/order-service
    ports:
      - "13002:13002"
    environment:
      - EUREKA_SERVER_LIST=http://center1:8761/eureka/,http://center2:8762/eureka/
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=13002
    external_links:
      - center1
      - center2
