version: "2"
services:

  #启动注册中心eureka-server集群 集中管理/服务注册/服务发现
  center1:
    hostname: center1
    image: lvqiang/register-center
    ports:
      - "8761:8761"
    environment:
      - HOSTNAME=center1
      - ADDITIONAL_EUREKA_SERVER_LIST=http://center2:8762/eureka/
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8761

  center2:
    hostname: center2
    image: lvqiang/register-center
    ports:
      - "8762:8762"
    environment:
      - HOSTNAME=center2
      - ADDITIONAL_EUREKA_SERVER_LIST=http://center1:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8762
    links:
      - center1