spring:
  application:
    name: hello-service
server:
  port: ${{SERVER_PORT}:10000}

security:
  oauth2:
    resource:
      id: hello-service
      user-info-uri: http://localhost:19000/user
      prefer-token-info: false

---
spring:
  profiles: docker
server:
  port: ${{SERVER_PORT}:10000}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_LIST}

security:
  oauth2:
    resource:
      id: hello-service
      user-info-uri: ${AUTH_SERVER_LIST}
      prefer-token-info: false