spring:
  application:
    name: sleuth-zipkin-monitor
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: admin
    password: admin

server:
  port: ${{SERVER_PORT}:9411}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_LIST}
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    ip-address: 192.168.99.100
    prefer-ip-address: true
