spring:
  application:
    name: order-service

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:order
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    schema: classpath:db/schema.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
server:
  port: 13000

eureka:
  client:
    serviceUrl:
      defaultZone: http://center1:8761/eureka/,http://center2:8762/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}

security:
  oauth2:
    resource:
      id: order-service
      user-info-uri: http://auth:19000/user
      prefer-token-info: false
