spring:
  application:
    name: order-service

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:order
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    schema: classpath:db/schema.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

server:
  port: 13000

---
spring:
  profiles: docker
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:order
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    schema: classpath:db/schema.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

server:
  port: ${{SERVER_PORT}:13000}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_LIST}

security:
  oauth2:
    resource:
      id: order-service
      user-info-uri: ${AUTH_SERVER_LIST}
      prefer-token-info: false

