spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://10.108.163.59:3306/product?useSSL=false
    username: root
    password: 12345678
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5Dialect

server:
  context-path: /product
  port: ${{SERVER_PORT}:11000}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_LIST}
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    ip-address: 192.168.99.100
    prefer-ip-address: true