spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:product
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    schema: classpath:db/schema.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none


server:
  port: 11000

---
spring:
  profiles: docker
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    schema: classpath:db/schema.sql


server:
  port: ${{SERVER_PORT}:11000}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_LIST}

