spring:
  application:
    name: hystrix-turbine-monitor
  rabbitmq:
    port: 5672
    username: admin
    password: admin
    host: 192.168.99.100

info:
  description: 监控数据聚合

server:
  port: ${{SERVER_PORT}:8888}

turbine:
  stream:
    port: 8989
