spring:
  application:
    name: app-api-gateway

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://center1:8761/eureka/,http://center2:8762/eureka/

zuul:
  routes:
    auth:
      path: /oauth/**
      sensitiveHeaders:
      serviceId: auth-service
    hello:
      path: /hello/**
      sensitiveHeaders:
      serviceId: hello-service
    product:
      path: /product/**
      sensitiveHeaders:
      serviceId: product-service
    coupon:
      path: /coupon/**
      sensitiveHeaders:
      serviceId: coupon-service
  add-proxy-headers: true

---
spring:
  profiles: docker
server:
  port: ${{SERVER_PORT}:8080}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_LIST}

zuul:
  routes:
    auth-service:
      path: /oauth/**
      sensitiveHeaders:
      serviceId: auth-service
    hello-service:
      path: /hello/**
      sensitiveHeaders:
      serviceId: hello-service
    product:
      path: /product/**
      sensitiveHeaders:
      serviceId: product-service
    coupon:
      path: /coupon/**
      sensitiveHeaders:
      serviceId: coupon-service
  add-proxy-headers: true
