spring:
  application:
    name: oauth-service

server:
  context-path: /uaa
  port: ${{SERVER_PORT}:8000}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_LIST}
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    ip-address: 192.168.99.100
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true